### ISSUE TITLE
질문 있습니다 !

### ISSUE THREAD

**Issue by hea955** [Wind-Kyle/python-fundamentals#1]
먼저, 좋은 글 잘 봤습니다!
보기 깔끔하게 잘 써주신 것 같고 대부분을 쉽게 이해 할 수 있도록 쉽게 작성한 글인것 같습니다.
특히, import this는 몰랐었는데 한번 보니 파이썬을 어떤 목적으로 개발했는지 좀 더 파악할 수 있었습니다.
보면서 궁금한점이 몇가지 있어 질문 드립니다.
인터프리터가 왜 다른 프로그래밍 언어보다 느린지,
그리고 Glue Language가 어떤 것을 하는지에 대한 설명이 있으면 좋을 것 같네요!
마지막으로 파이썬이 모바일에 약한 이유는 무엇인가에 대한 궁금증이 생겼습니다. 그 이유도 함께 있으면 더욱 편할 것 같습니다!!
그리고 객체 설명에서 불변쪽 부분은 이해가 살짝 힘든 것 같습니다 ㅠ 불변이 변경 불가능한 값을 갖는 것이 아니라고 나와있습니다. 객체들의 집합이 바뀌지 않으면 속해있는 값들도 변경이 바뀌지 않는 것이 맞는게 아닌가 싶은데, 이 부분은 이해가 잘 되지 않는 것 같습니다.

**Comment by Wind-Kyle** [comment]
모바일 같은 경우에는 결론부터 말씀드리자면 iOS는 swift, 안드로이드는 구글에서 자체적으로 Kotlin을 밀고있는 추세라서 모바일쪽은 파이썬은 지원이 아직 부족한 부분이 많기 때문입니다.

인터프리터는 쉽게 비유하자면 언어 해석기입니다. 인터프리터 역시 컴파일러처럼 프로그래밍 언어를 기계어로 변환해주는 역할을 합니다.
컴파일러는 전체 소스 코드를 목적 코드로 변환하여 그것을 재구성하고 빌드하는 방식이라면 인터프리터는 소스 코드 한줄마다 지속적으로 분석하면서 수행하기 때문에 컴파일러에 비해 느릴 수밖에 없는 것입니다. 대신 이렇게 한줄마다 분석하기 때문에 대화형으로 코드를 작성할 수 있다는 장점이 있어 데이터 분석할 때 탁월합니다.

인터프리터 언어 대부분이 글루 랭귀지(Glue Language)라는 특징을 가지고 있는데, 이는 말그대로 스크립트 언어가 어딘가에 붙이는 용도로 쓰는 풀처럼 다른 언어와 잘 붙는다는 특징을 가지고 있다는 의미입니다.

불변 (immutable) 객체란 말 그대로 한번 정의가 되면 그 값을 바꿀 수 없는 특징을 가진 객체를 의미하며 불변 객체 중 하나인 튜플(tuple) 자료형을 선언하고 값을 바꾸려하면 에러가 나는 것을 확인할 수 있는데, 이는 튜플이 한번 값이 정해지면 다시 바꿀 수 없는 불변형이기 때문입니다.

설명에 나와있는 부분을 잘 살펴보면 '불변 객체에 포함되어 있는 값이 가변 객체일 때, 그 가변 객체는 바꿀 수 있지만 불변 객체안에 들어있는 가변 객체 그 자체를 바꾸는 것은 불가능하다.'라고 되어있습니다.
튜플에 리스트 자료형이 하나 선언되어 있다고 가정해봅시다.

```python
a = [1, 2, 3]
b = (a, 1, 2, 3)
```

이렇게 되어있을 때, 튜플 b의 0번째 자리에는 리스트 a가 포함되어 있고 그 뒤에 각각 1, 2, 3이 포함되어 있습니다.
아래와 같이 리스트 a에 요소 4를 추가해본 뒤에,

```python
b[0].append(4)
```

튜플 b를 출력해보면 그 결과는 리스트 a에 요소 4가 추가되어 ([1, 2, 3, 4], 1, 2, 3)가 나옵니다.
그 이유는 a는 리스트이고, 리스트는 가변 (mutable) 객체이기 때문에 변할 수 있기 때문입니다.
그리고 여기서 리스트 c를 하나 선언합니다.

```python
c = [5, 6, 7]
```

튜플 b의 0번째에 아래와 같이 리스트 a를 리스트 c로 바꿔봅시다.

```python
b[0] = c
```

튜플은 불변형이기 때문에 튜플 안에 포함된 요소를 바꿀 수 없어서 에러가 발생합니다.
음, 이해가 잘 안되신다면 ` 존재론`적인 관점에서 생각해보시면 금방 이해가 되실 것 같습니다.

답변이 되셨나요?
