### ISSUE TITLE
import할 때 언더스코어에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by realblack0** [Wind-Kyle/python-fundamentals#4]
올려주신 강의노트 11. import, from, as, underscore, etc 에서 "모듈안에 포함된 식별자나 함수 앞에 언더스코어(_)를 붙이면 import 되지 않는다. " 라고 설명되어 있습니다. 

하지만 예제에서는 dir(my_module)을 통해 _value가 import되어있는 것을 확인했습니다.
```python
>>> import my_module
>>> dir(my_module)
['MyClass',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_value']
```

언더스코어가 붙은 함수나 식별자는 *를 이용해서 import할 때만 생략되고, 모듈 자체를 import할 때는 정상적으로 import 되는 것 같습니다. *를 쓸 때만 생략되는게 맞는지 확인 부탁드립니다.
```python
>>> from my_module import *
>>> dir(my_module)
['MyClass',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
```

강의 노트 덕분에 복습하기가 훨씬 수월해졌습니다!
항상 강의 노트 빠르게 정리해서 올려주시는 조교님 감사합니다!

**Comment by Wind-Kyle** [comment]
아.. 저거 제가 수정 안한채로 올린거 맞아요..
확인이 늦었습니다 ㅠㅠ
지적해주셔서 너무 감사드려요!!
